/* -*- Mode: C; tab-width: 2; indent-tabs-mode: t; c-basic-offset: 2 -*- */
//======================================================
// $Id: Bool.h,v 1.1 2005/05/12 21:54:47 plg Exp $
//======================================================

// autogenerated/refactored on Tue Aug 17 21:03:41 2004 by Paul L. Gatille <Paul.Gatille@free.fr>

/*
 * Copyright (c) 2004, Audemat-Aztec
*/


// Class SharedNum public methods

#ifndef __BOOL_H
#define __BOOL_H

#include "Toolbox.h"

// Class methods Identifiers

void Bool_Set(Bool_t Self, int value);

// --[public methods goes here ]--

// constructors
Bool_t tb_Bool(int val);
// factories (produce new object(s))

/*...*/
// mutators (change self)

/*...*/
// inspectors (don't change self)


/*...*/
// others





#endif

