/* -*- Mode: C; tab-width: 2; indent-tabs-mode: t; c-basic-offset: 2 -*- */
//======================================================
// $Id: Rpc_impl.h,v 1.1 2005/05/12 21:50:48 plg Exp $
//======================================================

// autogenerated/refactored on Wed Sep 22 14:13:45 2004 by Paul L. Gatille <Paul.Gatille@free.fr>

/*
 * Copyright (c) 2004, Paul Gatille
 * This file is part of Toolbox, an object-oriented utility library
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the "Artistic License" which comes with this Kit.
 *
 * This software is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the Artistic License for more
 * details.
*/



// Class Rpc private and internal methods and members


#ifndef __RPC_IMPL_H
#define __RPC_IMPL_H

#include "Toolbox.h"
#include "Rpc.h"

extern pthread_once_t __init_Rpc_once;
extern void init_Rpc_once();

struct Rpc_members {
	void *   methods; //__PRIVATE_
};
typedef struct Rpc_members * Rpc_members_t;



// Private default constructor
Rpc_t Rpc_new(); // mandatory default ctor (without params)

// members accessor
inline Rpc_members_t XRpc(Rpc_t Self);

#endif
