/* -*- Mode: C; tab-width: 2; indent-tabs-mode: t; c-basic-offset: 2 -*- */
//======================================================
// $Id: Bool_impl.h,v 1.1 2005/05/12 21:52:24 plg Exp $
//======================================================

// autogenerated/refactored on Wed Mar 30 18:06:27 2005 by Paul L. Gatille <Paul.Gatille@free.fr>

/*
 * Copyright (c) 2004, Audemat-Aztec
*/



// Class Bool private and internal methods and members


#ifndef __BOOL_IMPL_H
#define __BOOL_IMPL_H

#include "Toolbox.h"
#include "Bool.h"

extern pthread_once_t __init_Bool_once;
extern void init_Bool_once();
struct Bool_members {
	int  value;
};
typedef struct Bool_members *Bool_members_t;

// Private setters & getters

// Private default constructor
Bool_t Bool_new(); // mandatory default ctor (without params)

// members accessor
inline Bool_members_t XBool(Bool_t Self);

#endif
