/* -*- Mode: C; tab-width: 2; indent-tabs-mode: t; c-basic-offset: 2 -*- */
//===========================================================
// $Id: Bool.c,v 1.1 2005/05/12 21:52:24 plg Exp $
//===========================================================

// autogenerated/refactored on Wed Mar 30 18:10:17 2005 by Paul L. Gatille <Paul.Gatille@free.fr>

/*
 * Copyright (c) 2004, Audemat-Aztec
*/


/**
 * @file Bool.c
 */

/**
 * @defgroup Bool Class Bool_t
 * @ingroup GT_Utils
 * Class Bool
 *
 * description :
 *
 * ... here the header description
 */

#include <string.h>


#include "Toolbox.h"
#include "Memory.h"
#include "Error.h"
#include "Bool_impl.h"
#include "Scalars.h"
#include "tb_ClassBuilder.h"
#include "C_Castable_interface.h"
#include "Serialisable_interface.h"


static void       * Bool_free         (Bool_t Self);
static Bool_t       Bool_clone        (Bool_t Self);
static int          Bool_toInt        (Bool_t Self);
static char       * Bool_toStr        (Bool_t Self);
static void         Bool_marshall     (Bool_t marshalled, Num_t N, int level);
static Bool_t       Bool_unmarshall   (XmlElt_t xml);
static Tlv_t        Bool_toTlv        (Bool_t Self);
static Bool_t       Bool_fromTlv      (Tlv_t Tlv);
static void         Bool_dump         (Bool_t B, int level);
static Bool_t       Bool_set          (Bool_t B, int val);
static String_t     Bool_stringify    (Bool_t B);
static cmp_retval_t Bool_compare(Bool_t B1, Bool_t B2);
//-----------------------------------------------------
// Scalar Class overloaded methods
//-----------------------------------------------------
//-----------------------------------------------------
// tb_Object Class overloaded methods
//-----------------------------------------------------
// static tb_Object_t     SharedNumClone(tb_Object_t Self);
// static void            SharedNumDump(tb_Object_t Self);
// static tb_Object_t     SharedNumClear(tb_Object_t Self);
// static int             SharedNumCompare(tb_Object_t Self, tb_Object_t Other);
// static String_t        SharedNumStringify(tb_Object_t Self);


void setup_Bool_once(int OID);

inline Bool_members_t XBool(Bool_t Self) {
	return (Bool_members_t)((__members_t)tb_getMembers(Self, TB_BOOL))->instance;
}

void __build_bool_once(int OID) {

	/* OM_NEW and OM_FREE are mandatory methods */
	tb_registerMethod(OID, OM_NEW,                    Bool_new);
  tb_registerMethod(OID, OM_FREE,                   Bool_free);
  tb_registerMethod(OID, OM_DUMP,                   Bool_dump);
  tb_registerMethod(OID, OM_CLONE,                  Bool_clone);
  tb_registerMethod(OID, OM_SET,                    Bool_set);
  tb_registerMethod(OID, OM_STRINGIFY,              Bool_stringify);
  tb_registerMethod(OID, OM_COMPARE,                Bool_compare);

	tb_implementsInterface(OID, "C_Castable", 
												 &__c_castable_build_once, build_c_castable_once);
	tb_implementsInterface(OID, "Serialisable", 
												 &__serialisable_build_once, build_serialisable_once);

	tb_registerMethod(OID, OM_TOSTRING,               Bool_toStr);
	tb_registerMethod(OID, OM_TOINT,                  Bool_toInt);
	tb_registerMethod(OID, OM_MARSHALL,               Bool_marshall);
	tb_registerMethod(OID, OM_UNMARSHALL,             Bool_unmarshall);
	tb_registerMethod(OID, OM_TOTLV,                  Bool_toTlv);
	tb_registerMethod(OID, OM_FROMTLV,                Bool_fromTlv);

	//---------------------------------------------------
	// Scalar Class overloaded methods
	//---------------------------------------------------
	//---------------------------------------------------
	// tb_Object Class overloaded methods
	//---------------------------------------------------
	// 	tb_registerMethod(OID, OM_SHAREDNUMCLONE, SharedNumClone      );
	// 	tb_registerMethod(OID, OM_SHAREDNUMDUMP, SharedNumDump       );
	// 	tb_registerMethod(OID, OM_SHAREDNUMCLEAR, SharedNumClear      );
	// 	tb_registerMethod(OID, OM_SHAREDNUMCOMPARE, SharedNumCompare    );
	// 	tb_registerMethod(OID, OM_SHAREDNUMSTRINGIFY, SharedNumStringify  );

}


Bool_t Bool_ctor(Bool_t Self, int value) {
	/* specific ctor code goes here */
	Bool_members_t m = XBool(Self);
	m->value   = (value) ? 1 : 0;
	return Self;
}


/** Bool_t constructor
 *
 * oneliner header function description
 *
 * longer description/explanation
 *
 * @param arg1 desc of arg1
 * @param argn desc of argn
 * @return descrition of return values
 *
 * @see related entries
 * @ingroup Bool
 */
Bool_t tb_Bool(int value) {
	return Bool_ctor(Bool_new(), value);
}



Bool_t Bool_new() {
	tb_Object_t Self;
	//	pthread_once(&__init_Bool_once, init_Bool_once);
	Bool_members_t m;
	Self =  tb_newParent(TB_BOOL);

	Self->isA  =TB_BOOL;

	m = (Bool_members_t)tb_xcalloc(1, sizeof(struct Bool_members));
	Self->members->instance = m;

	if(fm->dbg) fm_addObject(Self);

	return Self;
}

void *Bool_free(Bool_t Self) {
	if(tb_valid(Self, TB_BOOL, __FUNCTION__)) {
		fm_fastfree_on();
		tb_freeMembers(Self);
		fm_fastfree_off();
		Self->isA = TB_BOOL; // requiered for introspection (as we are unwinding dtors stack)
    return tb_getParentMethod(Self, OM_FREE);
	}

  return NULL;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//   start of Autogenerated interfaces for inheritable functions
/////////////////////////////////////////////////////////////////////////////////////////////////////////////


static Bool_t Bool_clone(Bool_t Self) {
	return tb_Bool(XBool(Self)->value);
}


/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//   debug wrappers for class methods
/////////////////////////////////////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Class methods local implementations
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

void Bool_Set(Bool_t Self, int value) {
	XBool(Self)->value = (value) ? 1 : 0;
}




static int Bool_toInt(Bool_t Self) {
	return XBool(Self)->value;
}

static char *Bool_toStr(Bool_t Self) {
	return (XBool(Self)->value) ? "true" : "false";
}

static void Bool_marshall(String_t marshalled, Bool_t Self, int level) { 
	char indent[level+1];
	memset(indent, ' ', level);
	indent[level] = 0;
	tb_StrAdd(marshalled, -1, "%s<boolean>%d</boolean>\n", indent, XBool(Self)->value);
}

static Bool_t Bool_unmarshall(XmlElt_t xml) { 
	Bool_t B = NULL;
	Vector_t V;
	if((V = XELT_getChildren(xml)) != NULL &&
		 tb_getSize(V) >0) {
		B = tb_Bool(tb_toInt(XELT_getText(tb_Get(V, 0))));
	}
	return B;
}


static Tlv_t Bool_toTlv(Bool_t Self) {
	Bool_members_t m = XBool(Self);
	return Tlv(TB_BOOL, sizeof(int), (char *)&(m->value));
}

static Bool_t Bool_fromTlv(Tlv_t Tlv) {
	return tb_Bool(*(((int*)Tlv)+2));
}

static void Bool_dump(Bool_t B, int level) {
	if(tb_valid(B, TB_BOOL, __FUNCTION__)) {
		char *_b[] = {"false", "true"};
		int i;
		Bool_members_t m = XBool(B);
		for(i = 0; i<level; i++) fprintf(stderr, " ");

		fprintf(stderr, "<TB_BOOL ADDR=\"%p\" REFCNT=\"%d\" VALUE=\"%s\"/>\n",
						B, B->refcnt, _b[m->value]);
	}
}


static Bool_t Bool_set(Bool_t B, int val) {
	if(! tb_valid(B, TB_BOOL, __FUNCTION__)) return NULL;
	Bool_members_t m = XBool(B);
  m->value = val;

	return B;
}


static String_t Bool_stringify(Bool_t B) {
	char *_b[] = {"false" , "true"};
	return tb_String("%s", _b[XBool(B)->value]);
}

static cmp_retval_t Bool_compare(Bool_t B1, Bool_t B2) {
	if(XBool(B1)->value == XBool(B2)->value) return TB_CMP_IS_EQUAL;
	return TB_CMP_IS_LOWER; // not very accurate ...
}


//----------------------------------------------------
// Num Class overloaded methods
//----------------------------------------------------
//----------------------------------------------------
// Scalar Class overloaded methods
//----------------------------------------------------
//----------------------------------------------------
// tb_Object Class overloaded methods
//----------------------------------------------------
// tb_Object_t SharedNumClone(tb_Object_t Self) { }
// void SharedNumDump(tb_Object_t Self) { }
// tb_Object_t SharedNumClear(tb_Object_t Self) { }
// int SharedNumCompare(tb_Object_t Self, tb_Object_t Other) { }
// String_t SharedNumStringify(tb_Object_t Self) { }


/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//    public setters & getters methods goes here
/////////////////////////////////////////////////////////////////////////////////////////////////////////////





/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//    others class methods
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

